"""Global constants for Horizon UI."""

# Camera defaults
DEFAULT_CAMERA_INDEX = 0
DEFAULT_RESOLUTION = (640, 480)
DEFAULT_FPS = 30
FRAME_QUEUE_MAX_SIZE = 2

# Audio defaults
DEFAULT_SAMPLE_RATE = 16000
DEFAULT_AUDIO_CHANNELS = 1
DEFAULT_CHUNK_DURATION_MS = 30

# MediaPipe defaults
DEFAULT_MAX_HANDS = 1
DEFAULT_DETECTION_CONFIDENCE = 0.5
DEFAULT_TRACKING_CONFIDENCE = 0.5
LANDMARK_COUNT = 21

# Gesture classification
DEFAULT_CONFIDENCE_THRESHOLD = 0.75
DEFAULT_SMOOTHING_ALPHA = 0.3
DEFAULT_TEMPORAL_WINDOW = 15
GESTURE_COOLDOWN_MS = 200

# Cursor tracking
DEFAULT_CURSOR_SMOOTHING_ALPHA = 0.5
CURSOR_ALPHA_MIN = 0.25
CURSOR_ALPHA_MAX = 0.85
CURSOR_VELOCITY_LOW = 0.005
CURSOR_VELOCITY_HIGH = 0.05
DEFAULT_MIRROR_X = False

# Voice
VAD_MODE = 3  # webrtcvad aggressiveness (0-3)
VAD_FRAME_DURATION_MS = 30
SPEECH_PAD_DURATION_MS = 300
MIN_SPEECH_DURATION_MS = 250
ASR_BACKENDS = ("whisper", "vosk")

# Fusion
FUSION_ALIGNMENT_WINDOW_MS = 100
VOICE_OVERRIDE_GESTURE = True

# Performance targets
MAX_GESTURE_LATENCY_MS = 120
MAX_VOICE_LATENCY_MS = 500
MAX_CPU_PERCENT = 50
MAX_RAM_MB = 3500

# Overlay
DEFAULT_OVERLAY_OPACITY = 0.85
DEFAULT_CURSOR_SIZE = 24

# Plugin IPC
PIPE_NAME = r"\\.\pipe\HorizonUI"
IPC_TIMEOUT_MS = 5000
MAX_PLUGIN_MESSAGE_SIZE = 65536

# Paths
APP_NAME = "HorizonUI"
CONFIG_DIR = "config"
DEFAULT_SETTINGS_FILE = "default_settings.yaml"
GESTURE_MAPPINGS_FILE = "gesture_mappings.yaml"
VOICE_COMMANDS_FILE = "voice_commands.yaml"
MODELS_DIR = "models"
GESTURE_MODEL_FILE = "gesture_classifier.onnx"
